/*
 Navicat Premium Data Transfer

 Source Server         : test
 Source Server Type    : MySQL
 Source Server Version : 80026
 Source Host           : localhost:3306
 Source Schema         : dmsystem

 Target Server Type    : MySQL
 Target Server Version : 80026
 File Encoding         : 65001

 Date: 13/10/2021 19:49:57
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for form
-- ----------------------------
DROP TABLE IF EXISTS `form`;
CREATE TABLE `form`  (
  `form_id` int(0) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `html` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  PRIMARY KEY (`form_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 24 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of form
-- ----------------------------
INSERT INTO `form` VALUES (1, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (2, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">密码框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"请输入密码\">\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (3, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">密码框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"请输入密码\">\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (4, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">密码框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"请输入密码\">\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (9, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">日期选择：</label>\n                                <div class=\"col-sm-9\">\n                                    <div class=\"input-group date\">\n                                        <span class=\"input-group-addon\">日期</span>\n                                        <input type=\"text\" class=\"form-control\" value=\"\">\n                                    </div>\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (10, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">日期选择：</label>\n                                <div class=\"col-sm-9\">\n                                    <div class=\"input-group date\">\n                                        <span class=\"input-group-addon\">日期</span>\n                                        <input type=\"text\" class=\"form-control\" value=\"\">\n                                    </div>\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (11, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">日期选择：</label>\n                                <div class=\"col-sm-9\">\n                                    <div class=\"input-group date\">\n                                        <span class=\"input-group-addon\">日期</span>\n                                        <input type=\"text\" class=\"form-control\" value=\"\">\n                                    </div>\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (12, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">日期选择：</label>\n                                <div class=\"col-sm-9\">\n                                    <div class=\"input-group date\">\n                                        <span class=\"input-group-addon\">日期</span>\n                                        <input type=\"text\" class=\"form-control\" value=\"\">\n                                    </div>\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (13, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">日期选择：</label>\n                                <div class=\"col-sm-9\">\n                                    <div class=\"input-group date\">\n                                        <span class=\"input-group-addon\">日期</span>\n                                        <input type=\"text\" class=\"form-control\" value=\"\">\n                                    </div>\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (14, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">日期选择：</label>\n                                <div class=\"col-sm-9\">\n                                    <div class=\"input-group date\">\n                                        <span class=\"input-group-addon\">日期</span>\n                                        <input type=\"text\" class=\"form-control\" value=\"\">\n                                    </div>\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (15, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">密码框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"请输入密码\">\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (16, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">密码框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"请输入密码\">\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (17, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">密码框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"请输入密码\">\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (20, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">密码框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"请输入密码\">\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (21, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">下拉框：</label>\n                                <div class=\"col-sm-9\">\n                                    <select class=\"form-control\" name=\"\">\n                                        <option>选项 1</option>\n                                        <option>选项 2</option>\n                                        <option>选项 3</option>\n                                        <option>选项 4</option>\n                                    </select>\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (22, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div></form>\n                ');
INSERT INTO `form` VALUES (23, '表单标题', '\n                    <form role=\"form\" class=\"form-horizontal m-t\" id=\"list\">\n                            <div class=\"form-group\">\n                                <label class=\"col-sm-3 col-sm-offset-4 control-label\" style=\"font-weight:bold;font-size: large;\">表单标题</label>\n                            </div><div class=\"form-group\">\n                                <label class=\"col-sm-3 control-label\">文本框：</label>\n                                <div class=\"col-sm-9\">\n                                    <input type=\"text\" name=\"\" class=\"form-control\" placeholder=\"请输入文本\">\n                                </div>\n                            </div></form>\n                ');

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles`  (
  `role_id` int(0) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `namezh` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of roles
-- ----------------------------
INSERT INTO `roles` VALUES (1, 'student', '学生');
INSERT INTO `roles` VALUES (2, 'admin', '管理员');
INSERT INTO `roles` VALUES (3, 'aunt', '阿姨');

-- ----------------------------
-- Table structure for user_role
-- ----------------------------
DROP TABLE IF EXISTS `user_role`;
CREATE TABLE `user_role`  (
  `ID` int(0) NOT NULL AUTO_INCREMENT,
  `ur_user_id` int(0) NULL DEFAULT NULL,
  `ur_role_id` int(0) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `ur_user_id`(`ur_user_id`) USING BTREE,
  INDEX `ur_role_id`(`ur_role_id`) USING BTREE,
  CONSTRAINT `user_role_ibfk_1` FOREIGN KEY (`ur_user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `user_role_ibfk_2` FOREIGN KEY (`ur_role_id`) REFERENCES `roles` (`role_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of user_role
-- ----------------------------
INSERT INTO `user_role` VALUES (1, 1, 2);

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `user_id` int(0) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `password` varchar(300) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `salt` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `locked` smallint(0) NULL DEFAULT NULL,
  `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`user_id`, `email`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES (1, 'admin', 'a9d6967d289289ecea5bee10b8e582a8', '5522588431212800', 1, '1274650479@qq.com');

SET FOREIGN_KEY_CHECKS = 1;
